#!/bin/bash
pathTo="$(dirname $(realpath lab2))"
crontab -l > alarm
scr="$pathTo/bud $1 #bud"

function delete() {
	touch ./alarm.temp
	while IFS= read -r line; do
		if [ "$line" != "$1 $2 * * * $scr" ]; then
			echo "$line" >> ./alarm.temp
		fi
	done < ./alarm
	cp ./alarm.temp ./alarm
	rm ./alarm.temp
}

function edit() {
	while IFS= read -r line; do
		if [ "$line" == "$1 $2 * * * $scr" ]; then
			echo "$3 $4 * * * $scr" >> ./alarm
			delete $1 $2
		fi
	done < ./alarm
}

if [ "$#" == "5" ]; then
	edit $2 $3 $4 $5
fi
if [ "$#" == "4" ]; then
	delete $2 $3
fi
if [ "$#" == "3" ]; then
	echo "$2 $3 * * * $scr" >> ./alarm
fi
if [ "$#" == "0" ]; then
	out= grep "#bud" ./alarm
	echo "$out"
fi

crontab alarm
